#!/usr/bin/env node
// design-sync prepare step for @depot/web (run from the repo root).
//
// The design system lives INSIDE the @depot/web app — it has no standalone
// library entry, its components are default exports in kebab-case dirs, and its
// styling is Tailwind v4 utility classes generated at build time. This script
// produces the three inputs the converter needs, deterministically from
// .design-sync/config.json (the single source of truth for the component set):
//
//   1. packages/web/.ds-entry.tsx      — barrel of NAMED re-exports (default
//      exports become `export { default as <Name> }`) so the bundle lands every
//      component on window.DepotUI.<Name>.
//   2. packages/web/.ds-providers.tsx  — re-exports MemoryRouter so router-aware
//      components (Breadcrumbs, LinkCard, ErrorState) render in previews.
//   3. packages/web/dist/types/**      — TS declarations (tsc -b) the converter
//      reads for each component's prop contract.
//   4. packages/web/dist/ds-styles.css — the compiled Tailwind stylesheet
//      (cfg.cssEntry), with the brand webfont @import prepended.
//
// All generated files are gitignored; only this script + config.json are
// committed, so a fresh clone reproduces the exact build.

import { execSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const WEB = join(REPO, 'packages', 'web');
const cfg = JSON.parse(readFileSync(join(REPO, '.design-sync', 'config.json'), 'utf8'));

// Google Fonts webfont the app loads via <link> in index.html. Shipped as a
// remote @import so designs render in the real brand face (Atkinson
// Hyperlegible) — validate reports this as [FONT_REMOTE] (informational).
const FONT_IMPORT =
  "@import url('https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&display=swap');\n";

// ── 1 + 2. barrel + providers ──────────────────────────────────────────────
const lines = [
  '// AUTO-GENERATED by .design-sync/prepare-build.mjs — do not edit.',
  '// Barrel of design-system components for the design-sync bundle.',
];
const starred = new Set();
for (const [name, rel] of Object.entries(cfg.componentSrcMap)) {
  if (rel == null) continue;
  const abs = join(WEB, rel);
  if (!existsSync(abs)) {
    console.error(`! componentSrcMap: ${name} → ${rel} not found — skipped`);
    continue;
  }
  const isDefault = /export\s+default/.test(readFileSync(abs, 'utf8'));
  const spec = './' + rel.split('\\').join('/');
  if (isDefault) {
    // Default export → the component itself, under its PascalCase name. Also
    // re-export the file's NAMED exports so composition sub-parts that aren't
    // compound statics (e.g. TableHeader/TableRow/TableCell) reach the global.
    // `export *` never carries the default, so there's no clash; type-only
    // named exports erase at bundle time.
    lines.push(`export { default as ${name} } from '${spec}';`);
    if (!starred.has(spec)) {
      lines.push(`export * from '${spec}';`);
      starred.add(spec);
    }
  } else {
    lines.push(`export { ${name} } from '${spec}';`);
  }
}
writeFileSync(join(WEB, '.ds-entry.tsx'), lines.join('\n') + '\n');
console.error(`✓ .ds-entry.tsx: ${lines.length - 2} exports`);

writeFileSync(
  join(WEB, '.ds-providers.tsx'),
  '// AUTO-GENERATED by .design-sync/prepare-build.mjs — do not edit.\n' +
    "export { MemoryRouter } from 'react-router-dom';\n",
);
console.error('✓ .ds-providers.tsx');

// ── 3. TS declarations → dist/types ────────────────────────────────────────
console.error('» tsc -b (emitting declarations to dist/types) …');
execSync('pnpm --filter @depot/web run typecheck', { cwd: REPO, stdio: 'inherit' });

// ── 4. Tailwind v4 stylesheet → dist/ds-styles.css ─────────────────────────
const require = createRequire(pathToFileURL(join(WEB, 'package.json')));
const postcssMod = await import(pathToFileURL(require.resolve('postcss')));
const tailwindMod = await import(pathToFileURL(require.resolve('@tailwindcss/postcss')));
const postcss = postcssMod.default ?? postcssMod;
const tailwind = tailwindMod.default ?? tailwindMod;

process.chdir(WEB); // Tailwind v4 auto-detects content from the cwd tree.
const input = readFileSync('src/styles/main.css', 'utf8');
const result = await postcss([tailwind()]).process(input, {
  from: 'src/styles/main.css',
  to: 'dist/ds-styles.css',
});
writeFileSync(join(WEB, 'dist', 'ds-styles.css'), FONT_IMPORT + result.css);
console.error(`✓ dist/ds-styles.css: ${((FONT_IMPORT.length + result.css.length) / 1024).toFixed(0)} KB`);
