// Action type constants
export const APP_ACTIONS = {
  LOAD_INDEX_START: 'LOAD_INDEX_START',
  LOAD_INDEX_SUCCESS: 'LOAD_INDEX_SUCCESS',
  LOAD_INDEX_ERROR: 'LOAD_INDEX_ERROR',
  LOAD_FACTION_START: 'LOAD_FACTION_START',
  LOAD_FACTION_SUCCESS: 'LOAD_FACTION_SUCCESS',
  LOAD_FACTION_ERROR: 'LOAD_FACTION_ERROR',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  CLEAR_ERROR: 'CLEAR_ERROR'
} as const;