export const SETTINGS_ACTIONS = {
  LOAD_SETTINGS_START: 'LOAD_SETTINGS_START',
  LOAD_SETTINGS_SUCCESS: 'LOAD_SETTINGS_SUCCESS',
  LOAD_SETTINGS_ERROR: 'LOAD_SETTINGS_ERROR',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS'
} as const;
