// Action type constants
export const APP_ACTIONS = {
  LOAD_INDEX_START: 'LOAD_INDEX_START',
  LOAD_INDEX_SUCCESS: 'LOAD_INDEX_SUCCESS',
  LOAD_INDEX_ERROR: 'LOAD_INDEX_ERROR',
  LOAD_FACTION_START: 'LOAD_FACTION_START',
  LOAD_FACTION_ERROR: 'LOAD_FACTION_ERROR',
  UPDATE_OFFLINE_FACTIONS: 'UPDATE_OFFLINE_FACTIONS',
  LOAD_SETTINGS_SUCCESS: 'LOAD_SETTINGS_SUCCESS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  CLEAR_ERROR: 'CLEAR_ERROR'
} as const;
