name: CI Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Format check
        run: pnpm --filter depot-web run format
        
      - name: Lint check
        run: pnpm --filter depot-web run lint
        
      - name: Type check
        run: pnpm --filter depot-web run typecheck
        
      - name: Run tests
        run: pnpm --filter depot-web test