name: CI

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo apt-get install rsync
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn workspace depot-web build
      - name: rsync-deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-arv --delete'
          src: 'depot-web/dist/'
          dest: 'root@"${{secrets.SERVER_IP}}":/var/www/depot'
      - run: yarn workspace depot-cli start
      - name: rsync-deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-arv --delete'
          src: 'depot-cli/dist/data'
          dest: 'root@"${{secrets.SERVER_IP}}":/var/www/depot'